### PR TITLE
Order team members by enrolment number

### PR DESCRIPTION
**Pull request by ShreyasTheOne**
This was in response to issue: https://github.com/IMGIITRoorkee/omniport-frontend-groups/issues/6 from omniport-frontend-groups

### CODE REVIEW

**Review by algomaster99 — COMMENTED** [review]
The current student ordering seems good. For alumni, we can order by enrollment number in an ascending order? Your opinions, @ShreyasTheOne and @pradumangoyal .

**Comment by pradumangoyal** [comment]
Agreed! Seems better than having no-solution. What are we opting in the Maintainer site?

**Comment by algomaster99** [comment]
`-end_date, full_name`
But I think we should change that because there is a possibility that end_date might be `null` for few instances.

**Comment by ShreyasTheOne** [comment]
We could use `enrolment_number, full_name`

**Comment by algomaster99** [comment]
@ShreyasTheOne sounds good 👍🏼

**Comment by ShreyasTheOne** [comment]
@algomaster99 so should I remove the edits I had made in this PR and leave the current students order as it is?

**Comment by algomaster99** [comment]
Yes, because we are ordering both, student and alumni, by `enrolment_number, full_name`.

**Comment by ShreyasTheOne** [comment]
@algomaster99 @pradumangoyal I ordered them using enrolment number (after that no sorting is possible anyways), please review when possible.

**Review by algomaster99 — APPROVED** [review]

**Review by pradumangoyal — APPROVED** [review]

**Pull request merged**
